### ISSUE TITLE
Can you please create a seperate repository for decidim-ldap

### ISSUE THREAD

**Issue by itrich** [diputacioBCN/decidim-diba#40]
Dear decidim-diba team,

can you please create a seperate repository for decidim-ldap, so it's possible to fork it?

Best wishes,

Eduard

**Comment by xredo** [comment]
Hi @itrich 

The current maintainers of the project are being changed for new ones. Once the new maintainers have taken care of the project it will be a good moment to consider your request and make the necessary code changes to support it.

Kind regards

**Comment by enricostano** [comment]
Hi there,
any news about this issue? Would be easier to work on an upgrade to newer versions of Decidim.
Thanks!
